traefik:
  image: traefik
  command: -c /dev/null --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
  ports:
    - "801:801"
    - "8090:8090"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

whoami1:
  image: emilevauge/whoami
  labels:
    - "traefik.backend=whoami"
    - "traefik.frontend.rule=Host:whoami.docker.localhost"

whoami2:
  image: emilevauge/whoami
  labels:
    - "traefik.backend=whoami"
    - "traefik.frontend.rule=Host:whoami.docker.localhost"