version: '3'

services:

  # TRAEFIK
  traefik:
    image: traefik:1.4.0
    #command: --logLevel=DEBUG
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${SERVICE_HOME}/traefik/acme.json:/etc/traefik/acme.json
      - ${SERVICE_HOME}/traefik/traefik.toml:/etc/traefik/traefik.toml
    restart: always

  portainer:
  # PORTAINER
    image: portainer/portainer:1.15.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${SERVICE_HOME}/portainer:/data
    restart: always
    ports:
      - 9000:9000
    labels:
      - "traefik.enable=true"
      - "traefik.backend=portainer"
      - "traefik.frontend.rule=Host: portainer.krok.tk"
      - "traefik.port=9000"

  db:
     image: hypriot/rpi-mysql:5.5
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
  wordpress-mikael-blog:
     depends_on:
       - db
     image: wordpress:latest
     container_name: mikael-blog
     ports:
       - "8001:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_TABLE_PREFIX: mikael_
  wordpress-audrey-blog:
     depends_on:
       - db
     image: wordpress:latest
     container_name: audrey-blog
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_TABLE_PREFIX: audrey_
  phpmyadmin:
       image: phpmyadmin/phpmyadmin
       container_name: phpmyadmin
       environment:
        - PMA_ARBITRARY=1
       restart: always
       ports:
        - 8080:80
       volumes:
        - /sessions
volumes:
    db_data:

networks:
  local:
    driver: bridge