version: '3'

services:

  # TRAEFIK
  traefik:
    image: traefik:1.4.0
    #command: --logLevel=DEBUG
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${SERVICE_HOME}/traefik/acme.json:/etc/traefik/acme.json
      - ${SERVICE_HOME}/traefik/traefik.toml:/etc/traefik/traefik.toml
    restart: always

  # PORTAINER
  portainer:
    image: portainer/portainer:1.15.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${SERVICE_HOME}/portainer:/data
    restart: always
    ports:
      - 9000:9000
    labels:
      - "traefik.enable=true"
      - "traefik.backend=portainer"
      - "traefik.frontend.rule=Host: portainer.cheznous.tk"
      - "traefik.port=9000"

  # HOME ASSISTANT
  homeassistant:
    image: homeassistant/raspberrypi3-homeassistant:0.56.2
    volumes:
      - ${SERVICE_HOME}/homeassistant/tmp:/tmp
      - ${SERVICE_HOME}/homeassistant:/config
    network_mode: host
    logging:
      driver: "none"
    ports:
      - 8123:8123
    restart: always

  # ROOM ASSISTANT
  roomassistant:
    image: manfredmartin/room-assistant:latest-rpi
    volumes:
      - ${SERVICE_HOME}/roomassistant/config:/room-assistant/config:ro
    network_mode: host
#    logging:
#      driver: "none"
    ports:
      - 8123:8123
    restart: always

  # MOSQUITTO
  mosquitto:
    image: fstehle/rpi-mosquitto
    ports:
      - 1883:1883
    volumes:
      - ${SERVICE_HOME}/mosquitto/config:/mqtt/config:ro
    restart: always

  # INFLUXDB
  influxdb:
    image: influxdb:1.3.7
    ports:
      - 8086:8086
    volumes:
      - ${SERVICE_HOME}/influxdb:/var/lib/influxdb
    restart: always

  # GRAFANA
  grafana:
    image: fg2it/grafana-armhf:v4.6.0
    ports:
      - 3000:3000
    links:
      - influxdb
    environment:
      - GF_DEFAULT_INSTANCE_NAME=grafana
      - GF_SERVER_ROOT_URL=https://grafana.cheznous.tk
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - ${SERVICE_HOME}/grafana/lib:/var/lib/grafana
      - ${SERVICE_HOME}/grafana/log:/var/log/grafana
      - ${SERVICE_HOME}/grafana/conf:/etc/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.backend=grafana"
      - "traefik.frontend.rule=Host: grafana.cheznous.tk"
      - "traefik.port=3000"
    restart: always